version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: tempero-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: super@admin
      MYSQL_DATABASE: development
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: