version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: tempero-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: super@admin
      MYSQL_DATABASE: development
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  spring-backend:
    build: .
    container_name: tempero-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/development?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql-db

volumes:
  mysql-data:
